---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    type: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: insurance-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: insurance
          image: sharmilagaikwad29/insuranceproj
          ports:
            - ContainerPort: 8081
              hostPort: 8081
...			  
