---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
  labels:
    app: insurance-app
spec:
  replicas: 4
  selector:
    matchLabels:
      product: vehicle
  template:
    metadata:
      labels:
        product: vehicle
    spec:
      containers:
        - name: insurance-app
          image: sharmilagaikwad29/insuranceproj
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 1000m
              memory: 1600Mi
            requests:
              cpu: 500m
              memory: 300Mi
