---
apiVersion: v1
kind: Pod
metadata:
 name: insurance-app
 labels:
  author: sharmila
  type: proxy
spec:
 containers:
  - name: insurance-app
    image: sharmilagaikwad29/insuranceproj
    ports:
     ContainerPort: 8081
...
