---
apiVersion: v1
kind: Pod
metadata:
 name: insurance-pod
 labels:
  author: sharmila
  type: proxy
spec:
 containers:
  - name: appserver
    image: sharmilagaikwad29/insuranceproj
    ports:
     ContainerPort: 8081
...
