---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  labels:
    app: insurance-app
spec:
  ports:
    - name: insurance-app
      port: 8081
      targetPort: 8081
  type: NodePort
  selector:
    product: vehicle
