---
apiVersion: v1
kind: Service
metadata:
 name: insurance-service
spec:
 type: NodePort
 ports:
  - targetPort: 8081
    port: 8081
    protocol: TCP 
  selector:
  author: sharmila
  type: proxy
...
